name:                tir
version:             0.1.0.0
github:              "githubuser/tir"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tir#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- mtl
- random
- hmatrix
- hmatrix-gsl
- hmatrix-morpheus
- mltool
- intervals
- split
- config-ini
- text
- directory
- clock
- srtree
- evolution
- deepseq

library:
  source-dirs: src

executables:
  tir-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -eventlog
    - -O2
    - -optc-O3
    - -rtsopts
    dependencies:
    - tir

tests:
  tir-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -eventlog
    - -O2
    - -optc-O3
    - -rtsopts
    dependencies:
    - tir
